# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 05:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('street_type', models.CharField(max_length=15)),
                ('even_week_day', models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('Th', 'Thursday'), ('F', 'Friday'), ('Sa', 'Saturday'), ('Su', 'Sunday')], max_length=2)),
                ('even_week_number', multiselectfield.db.fields.MultiSelectField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th')], max_length=7)),
                ('even_start_time', models.DateTimeField()),
                ('even_duration', models.DurationField(choices=[(datetime.timedelta(0, 14400), '4 hours'), (datetime.timedelta(0, 21600), '6 hours')], default=datetime.timedelta(0, 14400))),
                ('odd_week_day', models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('Th', 'Thursday'), ('F', 'Friday'), ('Sa', 'Saturday'), ('Su', 'Sunday')], max_length=2)),
                ('odd_week_number', multiselectfield.db.fields.MultiSelectField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th')], max_length=7)),
                ('odd_start_time', models.DateTimeField()),
                ('odd_duration', models.DurationField(choices=[(datetime.timedelta(0, 14400), '4 hours'), (datetime.timedelta(0, 21600), '6 hours')], default=datetime.timedelta(0, 14400))),
                ('winter_hiatus', models.BooleanField(default=False)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetsweeper.Neighborhood')),
            ],
        ),
    ]
