# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetsweeper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='even_start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='street',
            name='odd_start_time',
            field=models.TimeField(),
        ),
    ]
