# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 10:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('streetsweeper', '0002_auto_20171023_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='street',
            name='even_duration',
        ),
        migrations.RemoveField(
            model_name='street',
            name='odd_duration',
        ),
        migrations.AddField(
            model_name='street',
            name='even_end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='street',
            name='odd_end_time',
            field=models.TimeField(default=datetime.datetime(2017, 10, 25, 10, 31, 49, 561541, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='street',
            name='neighborhood',
            field=models.CharField(choices=[('Winter Hill', 'Winter Hill'), ('East Somerville', 'East Somerville'), ('Prospect Hill', 'Prospect Hill'), ('Magoun Square', 'Magoun Square'), ('Ten Hills', 'Ten Hills'), ('Spring Hill', 'Spring Hill'), ('Powder House Square', 'Powder House Square'), ('Davis Square', 'Davis Square'), ('Ward Two', 'Ward Two'), ('Industrial Park', 'Industrial Park'), ('Mystic River', 'Mystic River'), ('West Somerville', 'West Somerville'), ('Tufts', 'Tufts')], max_length=255),
        ),
        migrations.DeleteModel(
            name='Neighborhood',
        ),
    ]
