# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 03:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='street',
            old_name='even_end_time',
            new_name='even_side_end_time',
        ),
        migrations.RenameField(
            model_name='street',
            old_name='even_start_time',
            new_name='even_side_start_time',
        ),
        migrations.RenameField(
            model_name='street',
            old_name='even_week_day',
            new_name='even_side_week_day',
        ),
        migrations.RenameField(
            model_name='street',
            old_name='even_week_number',
            new_name='even_side_week_number',
        ),
        migrations.RenameField(
            model_name='street',
            old_name='odd_end_time',
            new_name='odd_side_end_time',
        ),
        migrations.RenameField(
            model_name='street',
            old_name='odd_start_time',
            new_name='odd_side_start_time',
        ),
        migrations.RenameField(
            model_name='street',
            old_name='odd_week_day',
            new_name='odd_side_week_day',
        ),
        migrations.RenameField(
            model_name='street',
            old_name='odd_week_number',
            new_name='odd_side_week_number',
        ),
        migrations.RenameField(
            model_name='street',
            old_name='name',
            new_name='street_name',
        ),
        migrations.RemoveField(
            model_name='street',
            name='winter_hiatus',
        ),
    ]
